"""enhance job matching

Revision ID: 38f4cd09d80c
Revises: 6c2dd2f3e9ea
Create Date: 2026-07-10 15:11:59.170636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f4cd09d80c'
down_revision: Union[str, Sequence[str], None] = '6c2dd2f3e9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('strengths', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('resume_improvements', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('interview_probability', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('overall_feedback', sa.Text(), nullable=True))
    op.drop_column('job_matches', 'suggestions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('suggestions', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('job_matches', 'overall_feedback')
    op.drop_column('job_matches', 'interview_probability')
    op.drop_column('job_matches', 'resume_improvements')
    op.drop_column('job_matches', 'strengths')
    # ### end Alembic commands ###
