"""update job_matches table

Revision ID: 6c2dd2f3e9ea
Revises: 623bc872c341
Create Date: 2026-07-10 14:19:01.633132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2dd2f3e9ea'
down_revision: Union[str, Sequence[str], None] = '623bc872c341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('ats_score', sa.Integer(), nullable=True))
    op.add_column('job_matches', sa.Column('matched_skills', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('missing_skills', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('missing_keywords', sa.Text(), nullable=True))
    op.add_column('job_matches', sa.Column('suggestions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_matches', 'suggestions')
    op.drop_column('job_matches', 'missing_keywords')
    op.drop_column('job_matches', 'missing_skills')
    op.drop_column('job_matches', 'matched_skills')
    op.drop_column('job_matches', 'ats_score')
    # ### end Alembic commands ###
